keys:
  - &users: 
    - $enkre: age1qydnyugg6uws2wjv4u9gejkn35y85lz5kkq366rl7yc6peyruypq420lvp
  - &hosts:
    - &promethium:
    #- &zirconium:
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *enkre
      - *promethium
      #- *zirconium
